services:

  fogosptalerts:
    image: "ghcr.io/xhico/fogosptalerts:latest"
    container_name: "fogosptalerts"
    restart: "unless-stopped"
    volumes:
      - "fogosptalerts-data:/data"

volumes:
  fogosptalerts-data:
