services:

  # FogosPtAlerts
  fogosptalerts:
    container_name: "fogosptalerts"
    image: "fogosptalerts:latest"
    restart: "unless-stopped"
    env_file:
      - "stack.env"
    command: "python3 FogosPtAlerts.py"
    labels:
      - "wud.watch=false"