services:

  # FogosPtAlerts
  fogosptalerts:
    container_name: "fogosptalerts"
    image: "fogosptalerts:latest"
    hostname: "fogosptalerts.docker"
    restart: "unless-stopped"
    environment:
      - "FOGOS_EMAIL_SENDER_TO=${FOGOS_EMAIL_SENDER_TO}"