services:

  # FogosPtAlerts
  fogosptalerts:
    container_name: "fogosptalerts"
    image: "fogosptalerts:latest"
    hostname: "fogosptalerts.docker"
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"      
    env_file:
      - "stack.env"