services:

  # FogosPtAlerts
  fogosptalerts:
    container_name: "fogosptalerts"
    image: "fogosptalerts:latest"
    hostname: "fogosptalerts.docker"
    restart: "unless-stopped"
    environment:
      - "EMAIL_SENDER_TO=['francgf@gmail.com', 'milenereis90@gmail.com']"